### ISSUE TITLE
Which version to run?

### ISSUE THREAD

**Issue by doccosmos** [kylemcdonald/Parametric-t-SNE#1]
I am interested in training a T-SNE via the parametric form (and then applying it to a much larger data set as a classifier). What would be your recommendation as to which version of the parametric T-SNE algorithm to run? The wrapper around the Matlab/Octave one or one of the Keras/Theano solutions, and if so, which one?

**Comment by kylemcdonald** [comment]
the keras one is as good or better than the matlab/octave one.

the matlab one might run faster if you have a real copy of matlab to compile it, in octave it's too slow.
