### ISSUE TITLE
Which tSNE package are you using?

### ISSUE THREAD

**Issue by jaderabbit** [kylemcdonald/Parametric-t-SNE#2]
In your keras notebook, you import a tsne library which isn't in the requirements.txt. Which tsne package are you using?

**Comment by kylemcdonald** [comment]
It uses https://github.com/danielfrg/tsne but at this point I would modify the code to use https://github.com/lvdmaaten/bhtsne instead, which I've found to be the only implementation that really doesn't have any problems.
