### ISSUE TITLE
On t-SNE for MNIST

### ISSUE THREAD

**Issue by dkobak** [kylemcdonald/Parametric-t-SNE#4]
Hi Kyle, this is not really an issue with parametric t-SNE, so apologies for posting it here but I could not find a more appropriate way to contact you (somehow failed to find your email). 

My question is about running t-SNE on MNIST data. What I often experience myself is that some of the MNIST digits get "split" by t-SNE into two clusters, presumably stuck in a local minimum. This happens very often. The figure shown here https://github.com/DmitryUlyanov/Multicore-TSNE shows this issue with red cluster. The MNIST t-SNE plot shown here https://twitter.com/leland_mcinnes/status/963230617600184320 shows this issue even stronger with yellow cluster (look at the bottom). However, your plot shown here https://www.flickr.com/photos/kylemcdonald/26620503329/in/album-72157662596196708/ is completely free of such artifacts.

How did you achieve that? Did you try it out multiple times with random initialization until it worked? Did you use some specific initialization? Did you use some carefully selected parameters? (Perplexity, PCA preprocessing, early exaggeration, etc.) Some other trick?

I'm really curious. Thanks.

**Comment by dkobak** [comment]
Let me know if there is a more appropriate venue to contact you about that. Cheers!

**Comment by kylemcdonald** [comment]
i just used the defaults for multicore t-sne. if you look at the plot on flickr closer, you'll see the same artifacts. there's a purple chunk next to orange, pink next to blue, and pink next to green. it might just be that i don't draw my points as big so the effect doesn't look as pronounced.
